'use client';

import type { ComponentType, SVGProps } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@jobportal/ui';
import {
  Briefcase,
  Building2,
  ClipboardList,
  CreditCard,
  Flag,
  IndianRupee,
  LayoutDashboard,
  Megaphone,
  MessageCircle,
  ShieldCheck,
  UserCog,
  Users,
} from '@jobportal/ui/icons';

type NavIcon = ComponentType<SVGProps<SVGSVGElement>>;

// The Super Admin portal's navigation. The remaining surface (KYC & business
// verification) still lives in the older /admin console inside apps/web and adds
// one entry here when it moves — as support did in
// feature/sadmin-support-console, which also deleted its half of that subtree.
// The structure is the
// recruiter rail's, so adding an item is a one-line change and adding a
// collapsible group follows that portal's existing disclosure pattern.
//
// hrefs are basePath-RELATIVE. Next prefixes '/sadmin' itself, so writing
// '/sadmin/dashboard' here would resolve to /sadmin/sadmin/dashboard.
const NAV_ITEMS: readonly { href: string; label: string; icon: NavIcon }[] = [
  { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard as NavIcon },
  { href: '/jobs', label: 'Job review', icon: ClipboardList as NavIcon },
  // Sits directly under Job review because the two are a pair, and the labels
  // have to stay unambiguous: "Job review" is the moderation QUEUE (only jobs
  // awaiting or having had a decision), "Job Postings" is the master list of
  // every posting on the platform whatever its status. Two adjacent job entries
  // with vague names is the fastest way to land an admin in the wrong console.
  { href: '/job-postings', label: 'Job Postings', icon: Briefcase as NavIcon },
  // Completes the job block, and sits AFTER the two above rather than beside
  // Job review despite both being moderation. The distinction that matters to
  // whoever is scanning this rail is who raised the work: Job review is a queue
  // the PLATFORM generates (a posting routed for approval), while this one is
  // generated by USERS reporting something already live. The `Flag` icon is the
  // one apps/web already puts on the reporter's own "Report" control, so the
  // two ends of the feature share a glyph.
  { href: '/reports', label: 'Content reports', icon: Flag as NavIcon },
  { href: '/employers', label: 'Employer management', icon: Building2 as NavIcon },
  { href: '/candidates', label: 'Candidate management', icon: Users as NavIcon },
  { href: '/otp-sessions', label: 'OTP Sessions', icon: ShieldCheck as NavIcon },
  // Plans & billing overview. Sits after the two "who is on the platform"
  // consoles because it is answered in terms of them: a subscription is read as
  // "which employer is on which plan", so it follows Employer management rather
  // than opening the rail.
  { href: '/subscriptions', label: 'Subscriptions & Billing', icon: CreditCard as NavIcon },
  // Closes the money block, and sits AFTER Subscriptions & Billing because it is
  // the ledger BEHIND it: that console answers "who is on which plan", this one
  // answers "what was actually charged, and when". Reading them the other way
  // round is confusing — the plan is the thing, the payments are its history.
  //
  // `CreditCard` is deliberately NOT reused despite both being billing surfaces:
  // two adjacent rail rows carrying the same glyph is the fastest way to land an
  // admin in the wrong console, which is the same reasoning the Job review /
  // Job Postings pair records above.
  { href: '/transactions', label: 'Transaction & Revenue Log', icon: IndianRupee as NavIcon },
  // Support closes the rail, after the money block. It is placed LAST rather
  // than beside Content reports despite both being inbound queues, because the
  // two answer opposite questions: a content report is a THIRD PARTY complaining
  // about someone else's posting, while a support ticket is the raiser's own
  // problem — different subject, different lever, and filing them next to each
  // other invites working the wrong queue.
  //
  // The label is the SHORT form the owner asked for. "Support Ticket/Query
  // Management" is the accurate description but is twice the width of every
  // other row and would wrap in a 256px rail.
  //
  // `MessageCircle` is free in the icons barrel and is the only conversational
  // glyph there — Flag is already Content reports, and reusing it would pair the
  // two surfaces this comment exists to keep apart.
  { href: '/support', label: 'Support & Communication', icon: MessageCircle as NavIcon },
  // Broadcast Notifications closes the rail, directly after Support, and the two
  // are a deliberate pair: Support is the INBOUND queue (they write to us) and
  // this is the OUTBOUND one (we write to them). That is the same "same subject,
  // opposite direction" relationship the Job review / Job Postings pair records
  // above, and unlike the Content reports / Support pair further up, filing them
  // together does not risk working the wrong queue — an admin cannot mistake
  // composing an announcement for answering a ticket.
  //
  // It is LAST rather than first in that pair because the rail otherwise reads
  // as a descent from "who is on the platform" through "what they owe us" to
  // "what they have asked us"; sending is the only row that is not a queue of
  // work waiting, so it belongs at the end rather than interrupting that order.
  //
  // `Megaphone` was added to the icons barrel rather than reusing `Send` or
  // `Mail`. Both of those read as one message to one person, which is precisely
  // the mental model this console must not encourage.
  { href: '/broadcasts', label: 'Broadcast Notifications', icon: Megaphone as NavIcon },
  // Roles & Permissions closes the rail, below the outbound pair, because it is
  // the only entry that is not about the PLATFORM at all — every row above
  // answers a question about recruiters, seekers, jobs or money, and this one
  // answers a question about us. Last also means it does not interrupt the
  // descent from "who is on the platform" through "what they owe us" to "what
  // they have asked us".
  //
  // In practice it is the last row for a second reason: `system`/EDIT makes it
  // SUPER_ADMIN-only and unoverridable, so for every sub-admin the rail simply
  // ends at Broadcast Notifications.
  //
  // `UserCog` was appended to the icons barrel rather than reusing `ShieldCheck`,
  // which is already OTP Sessions. Two adjacent rail rows sharing a glyph is the
  // fastest way to land an admin in the wrong console — the same rule the Job
  // review / Job Postings and Subscriptions / Transactions pairs record above,
  // and it matters most here, where the wrong console is the one that grants
  // access to all the others.
  { href: '/roles', label: 'Roles & Permissions', icon: UserCog as NavIcon },
];

/**
 * Every rail href, in order — the input to the server-side scope filter.
 *
 * Derived from NAV_ITEMS rather than re-listed, so appending a row above is
 * still the one-line change it has always been and cannot leave a second list
 * behind. The (authed) layout passes these through visibleNavHrefs() and hands
 * the survivors back as `allowedHrefs`.
 */
export const NAV_ITEM_HREFS: readonly string[] = NAV_ITEMS.map((i) => i.href);

function isActive(pathname: string, href: string): boolean {
  return pathname === href || pathname.startsWith(`${href}/`);
}

// The rail sits on a FIXED navy surface (--color-primary-600) that does NOT
// follow the light/dark token swap, so its states are alpha-white rather than
// surface tokens — the same approach as the seeker dashboard and the recruiter
// portal. Contrast on #192249: white/70 = 8.3:1, cyan accent-500 = 5.2:1.
//
// FOCUS: theme.css's base rule paints :focus-visible with --color-ring
// (= --color-primary-500), which measures just 1.96:1 against this navy —
// below the 3:1 WCAG 1.4.11 floor, across the portal's entire primary
// navigation. Because theme.css sets an AUTHOR outline, the browser's own
// adaptive ring is suppressed and there is no fallback. Re-point the colour to
// white (~15:1); width and offset stay inherited. theme.css is shared with
// apps/web and must not be edited, so this is done at the call site.
const FOCUS_ON_NAVY = 'focus-visible:outline-white';

const ROW = `mt-0.5 flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors ${FOCUS_ON_NAVY}`;
const ROW_ACTIVE = 'bg-white/10 font-medium text-white';
const ROW_IDLE = 'text-white/70 hover:bg-white/5 hover:text-white';

const ICON = 'size-[18px] shrink-0';
// Brand cyan on the active row's icon only — the rail's single accent.
const ICON_ACTIVE = 'text-[var(--color-accent-500)]';
const ICON_IDLE = 'text-white/70';

/**
 * The rail, filtered to what this staff member can actually open.
 *
 * `allowedHrefs` is computed SERVER-side by lib/roles/nav-visibility.ts and
 * passed down as plain strings. Deliberately not computed here: this is a
 * 'use client' component, and a runtime value import of @jobportal/domain would
 * need that package adding to `transpilePackages` in next.config.ts — where its
 * absence produces an opaque build-time parse error rather than a useful one.
 *
 * Filtering the rail is presentation, not enforcement. Each page independently
 * calls requireAdminScope(), which 404s a scope miss whether or not a link to it
 * was ever drawn. Before this existed an out-of-scope link simply 404'd when
 * clicked — safe, but it invited staff to keep trying doors that would never
 * open, and it disclosed the shape of consoles they have no part in.
 *
 * `NAV_ITEMS` stays module-level and unfiltered so nav-visibility.test.ts can
 * read it off disk and fail the build when an entry has no ROUTE_SCOPES key.
 */
export function SidebarNav({ allowedHrefs }: { allowedHrefs: readonly string[] }) {
  const pathname = usePathname();
  const allowed = new Set(allowedHrefs);

  return (
    <nav aria-label="Super Admin">
      {NAV_ITEMS.filter(({ href }) => allowed.has(href)).map(({ href, label, icon: Icon }) => {
        const active = isActive(pathname, href);
        return (
          <Link
            key={href}
            href={href}
            aria-current={active ? 'page' : undefined}
            className={cn(ROW, active ? ROW_ACTIVE : ROW_IDLE)}
          >
            <Icon className={cn(ICON, active ? ICON_ACTIVE : ICON_IDLE)} aria-hidden="true" />
            {label}
          </Link>
        );
      })}
    </nav>
  );
}
