// Re-export only the lucide-react icons we use, so apps tree-shake cleanly.
// Add new icons here when needed; do NOT `import * from 'lucide-react'`.

export {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Bell,
  Bookmark,
  BookmarkCheck,
  Briefcase,
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  GraduationCap,
  IndianRupee,
  Info,
  LayoutDashboard,
  Linkedin,
  Link as LinkIcon,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  // Broadcast Notifications (/sadmin/broadcasts). Added rather than reusing
  // Send or Mail: SidebarNav's own comments record that two adjacent rail rows
  // sharing a glyph is the fastest way to land an admin in the wrong console,
  // and Mail/Send both read as "one message to one person" — the opposite of
  // what this console does.
  Megaphone,
  Menu,
  MessageCircle,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Trash2,
  TrendingUp,
  Twitter,
  User,
  UserCog,
  UserPlus,
  Users,
  X,
  Zap,
} from 'lucide-react';
