// Re-export only the lucide-react icons we use, so apps tree-shake cleanly.
// Add new icons here when needed; do NOT `import * from 'lucide-react'`.

export {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Bell,
  Bookmark,
  BookmarkCheck,
  Briefcase,
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Eye,
  EyeOff,
  Filter,
  IndianRupee,
  Info,
  Linkedin,
  Link as LinkIcon,
  Loader2,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MoreHorizontal,
  Plus,
  Search,
  Settings,
  Share2,
  Twitter,
  User,
  Users,
  X,
} from 'lucide-react';
